### ISSUE TITLE
upgrade golang to v1.22

### ISSUE THREAD

**Issue by lukas016** [ironcore-dev/libvirt-provider#195]
# Summary

Upgrade for golang 1.22.x can open door for improve of code.

More information about release:
https://tip.golang.org/doc/go1.22

## Subtasks

- [ ] upgrade golang version
- [ ] detect possible places which can use new features
  - [ ] implement it, if it is simple
  - [ ] create follow up issue for complex problem

Example: chi router can be replaced probably with router in standard library https://github.com/ironcore-dev/libvirt-provider/blob/main/provider/http/server.go#L28

## Motivation

We want to use latest stable version ideally
