### ISSUE TITLE
Resource and devices management architecture

### ISSUE THREAD

**Issue by lukas016** [ironcore-dev/libvirt-provider#63]
# Summary

We need prepare better solution for manage devices and resources.
We did pilot implementation for support Nvidia compute card (wrong marked as GPU). This implementation is naive and support only specific nvidia cards.

Current solution has many limitations:

- poor extensibility
- support only specific vendor
- simple device management
  - missing allocation of device
- doesn't support multiple gpu
- doesn't support sharing gpu between multiple vm

## Solution suggestion

- Plugin pattern
- General PCI device manager
- resource management

## Tasks

- [ ] prepare PoC
  - [ ] create concept docs
  - [ ] optional: example code, if it is needed
- [ ] discuss PoC with t-systems and sap
- [ ] discuss solution with architects
- [ ] prepare follow-up issues

## Motivation

We want to reach better extensibility of code.

**Comment by lukas016** [comment]
Duplicated issue: https://github.com/ironcore-dev/libvirt-provider/issues/147
This can be close.
